[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
watchPaths = ["apps/web/**"]

[deploy]
startCommand = "next start -H 0.0.0.0"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
