version: "3.8"

services:
  api:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/api:/app
    environment:
      - DEBUG=true

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
