'use client';

import { useState } from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import HitterProjectionsList from '@/components/projections/HitterProjectionsList';

export default function ProjectionsPage() {
  const [activeTab, setActiveTab] = useState('hitters');

  return (
    <div className="min-h-screen bg-gradient-to-br from-wine-plum via-wine-raisin to-wine-dark">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <h1 className="text-4xl font-bold text-white">MLB Stat Projections</h1>
            <Badge variant="secondary" className="bg-yellow-500/20 text-yellow-300 border-yellow-500/30">
              Beta
            </Badge>
          </div>
          <p className="text-wine-periwinkle text-lg">
            AI-powered MLB stat projections based on MiLB performance data
          </p>
        </div>

        {/* Disclaimer Alert */}
        <Alert className="mb-6 bg-blue-900/30 border-blue-500/30">
          <AlertDescription className="text-blue-200">
            These projections are experimental (Model R² = 0.344). Predictions are based on limited training data and
            actual MLB results may vary significantly. Use these as rough estimates, not definitive predictions.
          </AlertDescription>
        </Alert>

        {/* Data Availability Warning */}
        <Alert className="mb-6 bg-yellow-900/30 border-yellow-500/30">
          <AlertDescription className="text-yellow-200">
            <strong>Important:</strong> Most prospects will show "Projection not available". Projections require pre-debut
            MiLB stats, so they're only available for prospects who debuted in MLB between 2021-2025. Current MLB players
            and very young prospects won't have projections.
          </AlertDescription>
        </Alert>
        {/* Note: Requires HTTPS API endpoint in production */}

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="bg-wine-dark/50 border border-wine-periwinkle/20">
            <TabsTrigger
              value="hitters"
              className="data-[state=active]:bg-wine-periwinkle data-[state=active]:text-wine-dark"
            >
              Hitters
            </TabsTrigger>
            <TabsTrigger
              value="pitchers"
              disabled
              className="opacity-50 cursor-not-allowed"
            >
              Pitchers
              <Badge variant="outline" className="ml-2 text-xs border-wine-periwinkle/30 text-wine-periwinkle/70">
                Coming Soon
              </Badge>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="hitters" className="mt-6">
            <HitterProjectionsList />
          </TabsContent>

          <TabsContent value="pitchers" className="mt-6">
            <div className="bg-wine-dark/50 rounded-lg border border-wine-periwinkle/20 p-12 text-center">
              <h3 className="text-2xl font-bold text-white mb-4">
                Pitcher Projections Coming Soon
              </h3>
              <p className="text-wine-periwinkle mb-2">
                We're collecting more MLB pitcher data to train a reliable model.
              </p>
              <p className="text-wine-periwinkle/70 text-sm">
                Expected availability: Q1 2026
              </p>
            </div>
          </TabsContent>
        </Tabs>

        {/* Model Info Footer */}
        <div className="mt-8 bg-wine-dark/30 rounded-lg p-6 border border-wine-periwinkle/20">
          <h3 className="text-wine-periwinkle font-semibold mb-2">
            About These Projections
          </h3>
          <p className="text-white/70 text-sm mb-4">
            Hitter projections are generated by an XGBoost machine learning model trained on 399 prospects
            who transitioned from MiLB to MLB (2021-2025). The model predicts slash line stats (AVG/OBP/SLG)
            and rate stats (BB%, K%, ISO, OPS) based on pre-debut MiLB performance.
          </p>
          <div className="grid md:grid-cols-3 gap-4 text-sm">
            <div>
              <div className="text-wine-periwinkle font-medium">Model Performance</div>
              <div className="text-white">R² = 0.344 (moderate accuracy)</div>
            </div>
            <div>
              <div className="text-wine-periwinkle font-medium">Best Predictions</div>
              <div className="text-white">AVG, K%, OBP (R² &gt; 0.40)</div>
            </div>
            <div>
              <div className="text-wine-periwinkle font-medium">Model Version</div>
              <div className="text-white">improved_v1_20251020</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
