[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc", "g++"]
nixLibs = ["zlib", "libffi", "openssl"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt --timeout 600"
]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/alembic upgrade head && /opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
