[phases.setup]
nixPkgs = [
  "python311",
  "postgresql",
  "gcc",
  "zlib",
  "libffi",
  "openssl",
  # Playwright dependencies
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "cacert",
  "fontconfig",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "libxkbcommon",
  "pango",
  "cairo",
  "alsa-lib",
  "at-spi2-atk",
  "cups",
  "gtk3"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt --timeout 600",
  # Install Playwright browsers with dependencies
  "/opt/venv/bin/playwright install --with-deps chromium",
  # Verify Playwright installation
  "/opt/venv/bin/playwright install --help"
]

[phases.build]
cmds = []

[phases.release]
# Explicitly disable release phase - migrations run at startup in start.sh
cmds = []

[start]
cmd = "bash start.sh"
