[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc", "zlib", "libffi", "openssl"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt --timeout 600"
]

[phases.build]
cmds = ["chmod +x start.sh"]

[start]
cmd = "./start.sh"
