[phases.setup]
nixPkgs = [
  "python311",
  "postgresql",
  "gcc",
  "zlib",
  "libffi",
  "openssl"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt --timeout 600",
  # Skip Playwright browser installation in Railway environment
  # The browser automation features are not critical for the API in production
  # If needed, we can use a cloud-based browser service instead
  "echo 'Skipping Playwright browser installation for Railway deployment'"
]

[phases.build]
cmds = []

[phases.release]
# Explicitly disable release phase - migrations run at startup in start.sh
cmds = []

[start]
cmd = "bash start.sh"
