[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
watchPaths = ["apps/api/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
startCommand = "bash start.sh"
